on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Generate Version
        id: version
        run: |
          if [ -f version.txt ]; then
            current_version=$(cat version.txt)
            base_version=$(echo $current_version | cut -d'-' -f1)
            today=$(date +'%y-%m-%d')
            current_date=$(echo $current_version | cut -d'-' -f2,3,4)
            if [ "$today" = "$current_date" ]; then
              current_num=$(echo $current_version | cut -d'-' -f5)
              next_num=$(printf "%02d" $((10#$current_num + 1)))
            else
              next_num="00"
            fi
            new_version="$base_version-$today-$next_num"
          else
            new_version="0.1.0-$(date +'%y-%m-%d')-00"
          fi
          echo "$new_version" > version.txt
          echo "version=$new_version" >> $GITHUB_OUTPUT
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add version.txt
          git commit -m "Auto update version to $new_version"
          git tag "v$new_version"

      - name: Cache Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.yarn/cache
            .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            
      - name: Cache built output
        uses: actions/cache@v4
        with:
            path: build
            key: ${{ runner.os }}-spa-build-${{ hashFiles('**/*.md') }}
            restore-keys: |
                ${{ runner.os }}-spa-build-

      - name: Build graph's SPA
        uses: logseq/publish-spa@v0.3.0
        with:
          graph-directory: .
          theme-mode: light
          accent-color: green
          output-directory: build

      - name: Add a nojekyll file # to make sure asset paths are correctly identified
        run: touch $GITHUB_WORKSPACE/build/.nojekyll
      - name: Inject Logo
        run: cp -f $GITHUB_WORKSPACE/assets/logo.png $GITHUB_WORKSPACE/build/static/img/logo.png
      - name: Inject HTMLs
        run: chmod +x ./.github/scripts/inject_html.sh && ./.github/scripts/inject_html.sh
      - name: Add social preview
        run: cp -f $GITHUB_WORKSPACE/assets/social-preview.png $GITHUB_WORKSPACE/build/assets/social-preview.png

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: build
          folder: build
          clean: true
          single-commit: true

      - name: Push Version Changes
        run: |
          git push origin main --tags
          git push origin main
