on:
  push:
    branches: [dev]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run the action on a test graph and publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.yarn/cache
            .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build graph's SPA
        uses: logseq/publish-spa@v0.3.0
        with:
          graph-directory: .
          theme-mode: dark
          accent-color: cyan

      - name: Add a nojekyll file # to make sure asset paths are correctly identified
        run: touch $GITHUB_WORKSPACE/www/.nojekyll
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: dev-build
          folder: www
          clean: true
          single-commit: true
