on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.yarn/cache
            .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            
      - name: Cache built output
        uses: actions/cache@v4
        with:
            path: build
            key: ${{ runner.os }}-spa-build-${{ hashFiles('**/*.md') }}
            restore-keys: |
                ${{ runner.os }}-spa-build-

      - name: Build graph's SPA
        uses: logseq/publish-spa@v0.3.0
        with:
          graph-directory: .
          theme-mode: light
          accent-color: green
          output-directory: build

      - name: Add a nojekyll file # to make sure asset paths are correctly identified
        run: touch $GITHUB_WORKSPACE/build/.nojekyll
      - name: Inject Logo
        run: cp -f $GITHUB_WORKSPACE/assets/logo.png $GITHUB_WORKSPACE/build/static/img/logo.png
      - name: Inject HTMLs
        run: chmod +x ./.github/scripts/inject_html.sh && ./.github/scripts/inject_html.sh
      - name: Add social preview
        run: cp -f $GITHUB_WORKSPACE/assets/banner.png $GITHUB_WORKSPACE/build/assets/banner.png

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: build
          folder: build
          clean: true
          single-commit: true
